version: '3.4'

services:
  demo.webapi:
    image: ${DOCKER_REGISTRY}demowebapi
    build:
      context: .
      dockerfile: Demo.WebApi\Dockerfile


  demo.zipkinweb:
    image: ${DOCKER_REGISTRY}demozipkinweb
    build:
      context: .
      dockerfile: Demo.ZipKinWeb\Dockerfile


  demo.zipkinweb2:
    image: ${DOCKER_REGISTRY}demozipkinweb2
    build:
      context: .
      dockerfile: Demo.ZipKinWeb2\Dockerfile


  blogsync:
    image: ${DOCKER_REGISTRY}blogsync
    build:
      context: .
      dockerfile: BlogSYNC\Dockerfile


  demo.opentracing:
    image: ${DOCKER_REGISTRY}demoopentracing
    build:
      context: .
      dockerfile: Demo.OpenTracing\Dockerfile


  testdocker:
    image: ${DOCKER_REGISTRY}testdocker
    build:
      context: .
      dockerfile: TestDocker/Dockerfile

